### ISSUE TITLE
Move just a view? 

### ISSUE THREAD

**Issue by haleyngonadi** [damienromito/VisibleFormViewController#2]
Hi. This is exactly what I've been looking for but for some reason, it moves everything up, instead of the view with the textfield. Is there a way to fix this?

**Comment by damienromito** [comment]
What you want is an other behaviour, you have just to modify the code of VisibleFormViewController.m to do that. But I keep the current behaviour cause people generally need the full view moves. 
Anyway, thank you for you comment
